### ISSUE TITLE
Combat Follower Zone Button Ability

### ISSUE THREAD

**Issue by TruthNZ** [brittyazel/Ion#3]
I'm seeing the following issue with the Death Knight Champion Rottgut assigned as a Combat Follower - but I suspect it might be a bit more generic.

Combat Follower abilities show up as a Zone Ability Button. Firstly clicking this button isn't working. It's triggering a GCD, during which no other abilities can be used - but isn't actually triggering the combat ability.
Secondly the Zone Ability Button is incorrectly showing up when in areas it cannot be used - ie. While inside a Raid Zone. Interestingly even when in an area it shouldn't be able to be used, clicking on the Zone Button triggers a GCD cooldown.

The Combat Ability can be dragged/dropped from the Zone Button onto another action bar, and used there fine. When used from there (or via Macro, Script, etc) the Ability cooldown is correctly showing on the Zone Button (and also on the action bar button).

**Comment by brittyazel** [comment]
I am seeing this bug as well. I'll look into it!

**Comment by TruthNZ** [comment]
Looking at the code in Ion_ZoneAbilityBar. Does the method controlOnUpdate actually do anything?
I can't see the vars alphaTimer, alphaDir being used anywhere else.

**Comment by brittyazel** [comment]
Fixeed it I think. On line 156 of Ion_ZoneAbilityBar it explicitly said:
` self:SetAttribute("*macrotext1", "/cast Garrison Ability();")`
Which means that it is loading up the write button name/texture/etc, but then when it comes time to cast the spell it always is hardcoded to /cast Garrison Ability, which is why nothing would happen but the GCD would fire off.
I changed this line to read:
`self:SetAttribute("*macrotext1", "/cast " .. self.spellName .. "();")`
Thus ambiguating this call to be 'any' spell name specified when it loads up the bar.

The code is a still kind of messy though, and one thing that pisses me off is that the button can stick around even after you leave an area where it can't be used like you said above. I'm going to look into this next. Baby steps!

**Comment by brittyazel** [comment]
Ok all fixed :-)

It took a while, and in the process I learned a whole hell of a lot about how wow event handling works :-) Thanks for the challenge and for a decently easy fix to be my first major requested bug fix!

This fix will be added into the next release, which will be soon.

**Comment by TruthNZ** [comment]
I grabbed a direct copy from here, and can confirm it's working. Thanks!
